### PR TITLE
add editorconfig & rustfmt.toml,  run `rustfmt && eclint fix`

### PR DESCRIPTION
**Pull request by NukeManDan**
Thanks @rakanalh for the suggestion!
This supersedes #36 , to avoid merge conflicts after #33

- Uses the same file as https://github.com/substrate-developer-hub/substrate-node-template/blob/master/.editorconfig
- ran `rustfmt` on all `*.rs` files

### CODE REVIEW

**Comment by jimmychu0807** [comment]
With the editorconfig setting, I think we want to use tab in rust & toml files. But I see they are all replaced by spaces. What is our intent? By convention, we use tabs in rust & toml but spaces in javascript / typescript files.

**Comment by rakanalh** [comment]
I also thought that the convention at Parity is to use tabs... this is why i added the `.rustfmt.toml` there to use `hard_tabs = true`

https://github.com/substrate-developer-hub/substrate-parachain-template/pull/36/files#diff-1776b76bcca6d143dd8250bed589ada2b5f8b8ae28eb543cc6e91d3228a52c15R1

**Review by al3mart — APPROVED** [review]

**Comment by NukeManDan** [comment]
@jimmychu0807  https://github.com/substrate-developer-hub/substrate-node-template/blob/master/.editorconfig uses the same. If this is in error, let's get a new PR with the intended one.
https://github.com/paritytech/substrate/blob/master/.editorconfig is used in substrate, we can use this instead

**Comment by NukeManDan** [comment]
https://www.npmjs.com/package/eclint used with substrate convention.

**Pull request merged**
