### PR TITLE
Update rococo-v1 -> polkadot-v0.9.3

### LINKED ISSUE #29: Update to rococo-v1 -> polkadot dependancies
Rocco-v1 branch to be deprecated. Follow Polkadot releases from here on:
https://github.com/paritytech/polkadot/releases/tag/v0.9.2

Related: https://github.com/substrate-developer-hub/cumulus-workshop/issues/64

~While we are at it, we should also fix #28~ (new PR after)

### PR DESCRIPTION
**Pull request by NukeManDan**
https://github.com/paritytech/cumulus/tree/rococo-v1 
using `git merge --squash origin/polkadot-v0.9.3` against this as a base to see the commit diff & conflicts to compare to 😸

- [x] Use compact `Cargo.toml` notation per #17 cc @GopherJ
- [x] Remove concrete versions for deps (following cumulus, using branches only - note `Cargo.lock` will preserve a single commit when you build, and we will commit that in anything we release)
- [x] Update to cumulus `polkadot-v0.9.3` upstream deps as needed 
- [x] Update against new naming conventions and features in cumulus `polkadot-v0.9.2`
- [x] Successful build
- [x] Successful test vs. `polkadot-v0.9.3` relay chain.
  - ~Register Parachain, produce blocks~ Westend issues!
- [x] Update workshop to reflect new flow for `ParaId`

Closes #29

### CODE REVIEW

**Comment by NukeManDan** [comment]
Ready for a review, it builds and is working as expected, minus the stuff mentioned below. 

## Outstanding issues:
- Westend is up to the right runtime, but Rococo is not for this Polkadot v0.9.2 commit. Another PR here on the template will need to update.
    - `ReportLongevity` in BABE configuration I think is to blame: the time to get a parachain included is too long for testing. 
    - We should consider a Polkadot local relay chain that has very fast times for this, rococo is OK, but many testers think something is wrong while they don't get blocks after the sudo parachains registration.
- missing docs for `commands::run()` function... not sure why, It's documented.

### Runtime `lib.rs` notes:
- Randomness flip pallet is included, but the api is commented out. This may be broken, and should be fixed or removed.
- Benchmarking is added in CLI, closing #28 🎉  (untested!)
- `frame_system_rpc_runtime_api` and `pallet_transaction_payment_rpc_runtime_api` are implimented here, but not in cumulus, not 100% sure if this is correct.
- no cumulus ping or assets pallets used
- cleanup of deps, moving to `use` statments where it seemed logical vs in line
- introduce `UNIT` constants, replacing `ROC` in runtime (may have frontend template ramifications?)
- use of `RococoNetwork/Location` -> `RelayNetwork/Location` this may be incorrect, or should be renamed to reflect something else?
- a few unused imports and use statements not included, but used in cumulus

### Node `service.rs` notes:
- `parachain_build_import_queue` and `start_node` don't imply a network (like rococo) is this ok? Can we target generic relay chains here? 
- a few unused imports and use statements not included, but used in cumulus

### Node `chain_spec.rs` notes:
- Added note: `Extensions { relay_chain: "westend-dev".into(), // NOTE YOU MUST SET THE RIGHT RELAY CHAIN HERE! ...` 
    - Hard coded to `westend-dev` ... Should a CLI command be introduced to allow for setting this?

### Node `commands.rs` notes:
- Hard coded to `westend-dev` for relay_id string... Should a CLI command be introduced to allow for setting this?

### Build times 😭 

The build _requires_ that you build _every Polkadot runtime! This is very very heavy! It is possible to only enable building of the runtime(s) you need to target? I preseume for a collator this would be itself and the target relay chain? The worst offenders are the `*-service` builds, `polkadot-service` being the heaviest, I think as it requires building all runtimes..?

**Comment by al3mart** [comment]
I think we can focus the next version https://github.com/paritytech/cumulus/tree/polkadot-v0.9.3 as it has been release but this PR wasn't merged

**Comment by NukeManDan** [comment]
- tested to work with all deps from polkadot & cumulus & substrate v0.9.3 .
- readme updated with proper instructions.

Ready for a review & merge 🤞🏼

**Review by al3mart — APPROVED** [review]
Looking good.

**Pull request merged**
