### PR TITLE
Adding para_id constant

### PR DESCRIPTION
**Pull request by al3mart**
[Meanwhile](https://github.com/paritytech/cumulus/issues/530) it may be worth adding para_id constant to have a better UX

### CODE REVIEW

**Review by NukeManDan — CHANGES_REQUESTED** [review]
This makes sense to me! Can we first get some docs around this in the README and maybe a companion in the workshop too?

I _think_ the use of a flag would not be required... in fact, we may instead try and change upstream such that this lives within the chainspec or some other config file? It would help remove the footgun here and then something like #48 where at runtime, it would fail without something actually used that made sense. 🤔

**Comment by al3mart** [comment]
Integrating #paritytech/cumulus/pull/739  closes the PR

**Comment by samelamin** [comment]
We recently deployed to westend and faced the exact same issue

I think the underlying problem might be a lack of documentation or awareness that the spec generated will need the para id changed when it is created. I might be wrong but I did not see it highlighted anywhere and its hard to test against it because the paraId is then ignored in a test environment leading to false confidence that the chain and setup are ready for a live network



Perhaps highlight that in the docs for launching a parachain?

**Comment by NukeManDan** [comment]
:sob:  sorry for this footgun everyone, now in #82 we enforce you to set this inthe chain spec, and by default (for now at least) this is _broken_ for almost everyone using `1000` as the hard coded value (`2000` is the first availbe fro normal ID reservation)

Subscribe to this issue to track a doc that outlines this: https://github.com/substrate-developer-hub/substrate-docs/issues/513

**Pull request closed without merging**
