### PR TITLE
pay in foreign currency

### PR DESCRIPTION
**Pull request by justinzhou93**

### CODE REVIEW

**Comment by NukeManDan** [comment]
Justin - please edit your settings!!!

**Comment by NukeManDan** [comment]
I don't want to have to ask again please @justinzhou93

**Comment by justinzhou93** [comment]
i'm sorry again for this! i tried the git remote origin and it didn't work for me :( i set the remote origin to our fork and while the branch pushed to the right fork, it still seems like it didn't open against the correct repo. i'm playing around with the settings on our fork's branches to see if i can set the proper default when opening a PR

**Comment by NukeManDan** [comment]
maybe you use a tool like github desktop or something? Something belies you are trying to make a PR here. 
As you are a fork, on the gh page to make a PR you may default to target this repo instead of your own. Perhaps you need to change in gh settings.

**Pull request closed without merging**
